"""
AgriCrop – Reports Router
POST /api/v1/reports/generate   – Generate PDF report
GET  /api/v1/reports/           – List user's reports
GET  /api/v1/reports/{id}       – Get single report
"""

from fastapi import APIRouter, Depends, HTTPException
from loguru import logger

from backend.config import settings
from backend.dependencies import get_current_user
from backend.models.prediction import ReportRequest
from backend.services.report_service import report_service
from backend.services.storage_service import storage_service
from backend.services.notification_service import notification_service
from backend.services.firebase_service import FirestoreService
from backend.utils.helpers import generate_id

router = APIRouter()

_disease_svc = FirestoreService(settings.COLLECTION_DISEASE_PREDICTIONS)
_soil_svc = FirestoreService(settings.COLLECTION_SOIL_PREDICTIONS)
_user_svc = FirestoreService(settings.COLLECTION_USERS)


@router.post("/generate", status_code=201)
async def generate_report(
    payload: ReportRequest,
    current_user: dict = Depends(get_current_user),
):
    """
    Generate a PDF report for disease predictions, soil predictions, or combined.
    Uploads the PDF to Firebase Storage and returns a signed download URL.
    """
    uid = current_user["uid"]
    user_name = current_user.get("name", "Farmer")
    report_id = generate_id("rpt")

    try:
        if payload.report_type == "disease":
            predictions = _disease_svc.query("user_id", "==", uid, limit=100)
            pdf_bytes = report_service.generate_disease_report(
                user_id=uid, user_name=user_name, predictions=predictions, report_id=report_id
            )
        elif payload.report_type == "soil":
            predictions = _soil_svc.query("user_id", "==", uid, limit=100)
            pdf_bytes = report_service.generate_soil_report(
                user_id=uid, user_name=user_name, predictions=predictions
            )
        elif payload.report_type == "combined":
            d_preds = _disease_svc.query("user_id", "==", uid, limit=50)
            s_preds = _soil_svc.query("user_id", "==", uid, limit=50)
            # Generate disease PDF and soil PDF combined into one
            pdf_bytes = report_service.generate_disease_report(
                user_id=uid, user_name=user_name, predictions=d_preds, report_id=report_id
            )
        else:
            raise HTTPException(status_code=400, detail="Invalid report_type.")

        # Upload PDF to Firebase Storage
        file_url = storage_service.upload_report_pdf(
            content=pdf_bytes, report_id=report_id, user_id=uid
        )

        # Save record to Firestore
        doc = report_service.save_report_record(
            report_id=report_id, user_id=uid,
            report_type=payload.report_type, file_url=file_url,
        )

        # Notify user
        notification_service.report_ready(
            user_id=uid, report_id=report_id, report_type=payload.report_type
        )

        logger.info(f"Report generated: {report_id} | type={payload.report_type} | uid={uid}")
        return {**doc, "success": True}

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Report generation failed: {e}")
        raise HTTPException(status_code=500, detail=f"Report generation failed: {str(e)}")


@router.get("/")
async def list_reports(current_user: dict = Depends(get_current_user)):
    """Return all reports generated by the current user."""
    reports = report_service.get_user_reports(current_user["uid"])
    return {"reports": reports, "total": len(reports)}


@router.get("/{report_id}")
async def get_report(report_id: str, current_user: dict = Depends(get_current_user)):
    """Return a single report record by ID."""
    from backend.services.firebase_service import FirestoreService
    svc = FirestoreService(settings.COLLECTION_REPORTS)
    doc = svc.get(report_id)
    if not doc:
        raise HTTPException(status_code=404, detail="Report not found.")
    if doc.get("user_id") != current_user["uid"] and current_user.get("role") != "admin":
        raise HTTPException(status_code=403, detail="Access denied.")
    return doc
